FROM inseefrlab/jupyter-datascience:py3.7.6-spark3.1.1

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

RUN apt-get update \
    && apt-get install -y software-properties-common  \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get install --no-install-recommends -y git ffmpeg libsm6 libxext6 poppler-utils  \
    && pip install --upgrade pip setuptools wheel

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /root/.cache/pip

RUN python -m spacy download fr_core_news_lg

COPY download_doctr_models.py .
RUN python download_doctr_models.py

COPY . .
WORKDIR .
