prepare:
  train_split: 0.80
  seed: 42
  debug: False

featurize_fdp:
  data_augmentation: True
  min_df: 0.2

featurize_cni:
  data_augmentation: False
  min_df: 0.2

train_fdp:
  optimize: False
  n_iter: 50
  n_estimators: 200
  learning_rate: 0.06
  max_depth: 65
  max_leaf_nodes: 60

train_cni:
  optimize: False
  n_iter: 50
  n_estimators: 200
  learning_rate: 0.2
  max_depth: 3
  max_leaf_nodes: 12

eval:
