prepare:
  train_split: 0.80
  seed: 42
  debug: True

featurize_fdp:
  data_augmentation: True

featurize_cni:
  data_augmentation: False

train:
  optimize: True
  n_iter: 10
  n_estimators: 10

eval:
