prepare:
  train_split: 0.80
  seed: 42
  debug: False

featurize_fdp:
  data_augmentation: True
  min_df: 0.2

featurize_cni:
  data_augmentation: False
  min_df: 0.2

train:
  optimize: True
  n_iter: 50
  n_estimators: 200

eval:
