prepare:
  train_split: 0.80
  seed: 20170428
  debug: True

featurize_fdp:
  data_augmentation: True

featurize_cni:
  data_augmentation: False

train:
  optimize: True
  n_iter: 1
  n_estimators: 3

eval:
