prepare:
  train_split: 0.80
  seed: 42
  debug: False

featurize_fdp:
  data_augmentation: True

featurize_cni:
  data_augmentation: False

train:
  optimize: True
  n_iter: 50
  n_estimators: 200

eval:
