name: Python package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install dvc[s3]
    - name: Add minio credentials
      env:
        URL: ${{ secrets.URL }}
        OURURL: ${{ secrets.OURURL }}
        OURKEY: ${{ secrets.OURKEY }}
        OURPASSWORD: ${{ secrets.OURPASSWORD }}
      run: |
        dvc remote add -d minio $URL -f --local
        dvc remote modify minio endpointurl $OURURL --local
        dvc remote modify minio access_key_id $OURKEY --local
        dvc remote modify minio secret_access_key $OURPASSWORD --local
    - name: Pull Data
      run: |
        dvc pull data_dvc/cni_recto/model
        dvc pull data_dvc/salary/model
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: rob192/ocr-xtract
        tags: latest

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}